name: Generate Keystore
on:
  push:
    paths:
      - '.github/workflows/generate-keystore.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore android/app/naino-release.keystore -alias naino -keyalg RSA -keysize 2048 -validity 10000 -storepass nainopass -keypass nainopass -dname "CN=Naino, OU=Academy, O=Naino, L=City, S=State, C=IN"
      - name: Commit Keystore
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add android/app/naino-release.keystore
          git commit -m "chore: generated permanent release keystore"
          git push
